### ISSUE TITLE
using observations and actions in summarizer

### ISSUE THREAD

**Issue by ShirelJosef** [zhihanyang2022/CleanRL#3]
Hi 
In your article you note that "unrolling an RNN over the sequence of observations and actions"
However, going through your code, I only find that the recurrent summarizer is using observations only:
```python
actor_summary = self.actor_summarizer(b.o)
```
Can you please clarify that mismatch for me? What am I missing

**Comment by zhihanyang2022** [comment]
Hi, past actions are padded to `b.o` within the environments themselves (though not for all environments). For example, for DMC cartpole swingup:

```{python}
def va():
    return dmc2gym.make(domain_name="cartpole", task_name="swingup", keys_to_exclude=['position'], frame_skip=5, track_prev_action=True)
```
See the `track_prev_action` argument?

Things work more or less similarly for other environments.
