### ISSUE TITLE
Why is the observation sequence passed into the RNN module rather than the historical sequence of observations and actions?

### ISSUE THREAD

**Issue by yanler** [zhihanyang2022/CleanRL#4]
Hi，thank you for providing this good work. But i still have a little question. In the paper, history h_t is defined as the historical sequence of observations and actions like (o_1,a_1,……o_T,a_T). However, in the code implementation, the input to RNN is an observation sequence, which means that the history is summarized based on the historical observation sequence. Is this different from the description in the paper?

Here is the part of the code that corresponds to my question（in offpcc/algorithms_recurrent/recurrent_ddpg）：
actor_summary = self.actor_summarizer(b.o)  
critic_summary = self.critic_summarizer(b.o)

**Comment by zhihanyang2022** [comment]
Please see #3 for an answer.
